# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "servidorftp"

  # Red dentro de clase
  config.vm.network "public_network"

  config.vm.provision "shell", path: "provision.sh"

end